function build_simulink_model()
%BUILD_SIMULINK_MODEL  Generates adaptive_path_planning.slx programmatically.
%
% The model is a minimal Simulink integration AROUND the existing Python A*
% planner in main2_collision_free.py (via matlab_bridge.py):
%
%   Scenario/Environment State -> Obstacle State -> Prediction
%        -> Python Code block (EXISTING PathPlanner / A*)
%        -> EGO Motion (Python Code block, bounded kinematics, no teleport)
%        -> Collision/Safety Validation -> Metrics / Scopes
%
% Requires MATLAB R2025a+ (Python Code block) and pyenv configured to a
% Python interpreter that has pygame/numpy/pygltflib installed.

model = 'adaptive_path_planning';
DT = 0.02;                 % 50 Hz base step (commensurate with PLAN_DT)
PLAN_DT = 0.2;             % periodic replanning rate

%% Codegen on local drive (mapped/network drives break the cgxe build)
cgdir = fullfile(getenv('TEMP'), 'sl_codegen');
if ~isfolder(cgdir), mkdir(cgdir); end
Simulink.fileGenControl('set', 'CacheFolder', cgdir, ...
    'CodeGenFolder', cgdir, 'createDir', true);

if bdIsLoaded(model), close_system(model, 0); end
if isfile([model '.slx']), delete([model '.slx']); end
new_system(model); open_system(model);

%% --- Blocks -------------------------------------------------------------
add_block('simulink/Sources/Clock', [model '/Simulation Time'], ...
    'Position', [40 40 70 60]);

% 1) Scenario / Environment State -----------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model '/Scenario Environment State'], 'Position', [110 20 240 90]);
set_matlab_function(model, 'Scenario Environment State', char([ ...
"function [obs, goal] = fcn(t)" newline ...
"% Indian-road validation scenario. Obstacle matrix rows:" newline ...
"% [type_code, x(px), y(px), speed(px/s), heading(rad)]" newline ...
"% codes: 1 car  2 truck  3 bus  4 auto_rickshaw  5 two_wheeler" newline ...
"%        6 bicycle  7 pedestrian  8 pushcart  9 animal  10 pothole" newline ...
"obs = zeros(8,5);" newline ...
"obs(1,:) = [5, 700, 340, 0, 0];        % stopped two-wheeler (static blockage)" newline ...
"obs(2,:) = [1, 1500 + 35*t, 420, 35, 0];  % moving car, same lane" newline ...
"obs(3,:) = [7, 1800, 330 + 10*t, 10, pi/2]; % pedestrian crossing" newline ...
"goal = [2500; 400];" newline ...
]));

% Obstacle state bus selector (pass-through label block for readability) --
add_block('simulink/Signal Routing/Mux', [model '/Obstacle State'], ...
    'Inputs', '1', 'Position', [285 40 290 60]);

% 2) Prediction ------------------------------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model '/Prediction'], 'Position', [330 130 470 200]);
set_matlab_function(model, 'Prediction', char([ ...
"function [pred, ttc] = fcn(obs, ego)" newline ...
"% Constant-velocity short-horizon prediction + time-to-collision." newline ...
"H = 1.5;" newline ...
"pred = obs;" newline ...
"for i = 1:8" newline ...
"    if obs(i,1) > 0" newline ...
"        pred(i,2) = obs(i,2) + obs(i,4)*cos(obs(i,5))*H;" newline ...
"        pred(i,3) = obs(i,3) + obs(i,4)*sin(obs(i,5))*H;" newline ...
"    end" newline ...
"end" newline ...
"ttc = inf;" newline ...
"fx = cos(ego(4)); fy = sin(ego(4));" newline ...
"for i = 1:8" newline ...
"    if obs(i,1) <= 0, continue; end" newline ...
"    rx = obs(i,2)-ego(1); ry = obs(i,3)-ego(2);" newline ...
"    along = rx*fx + ry*fy;" newline ...
"    if along < 0, continue; end" newline ...
"    ovx = obs(i,4)*cos(obs(i,5)); ovy = obs(i,4)*sin(obs(i,5));" newline ...
"    closing = (ego(3)-ovx)*fx + (0-ovy)*fy;" newline ...
"    if closing > 1" newline ...
"        ttc = min(ttc, along/closing);" newline ...
"    end" newline ...
"end" newline ...
]));

% 3) Python A* Planner (EXISTING main2_collision_free.PathPlanner) --------
add_block('simulink/User-Defined Functions/Python Code', ...
    [model '/Python AStar Planner'], 'Position', [330 20 470 90]);
ss = get_param([model '/Python AStar Planner'], 'SymbolSpec');
s = ss.addSymbol('ego');         s.Scope = 'Input';  s.Size = '4';
s = ss.addSymbol('obs');         s.Scope = 'Input';  s.Size = '[8,5]';
s = ss.addSymbol('goal');        s.Scope = 'Input';  s.Size = '2';
s = ss.addSymbol('path_x');      s.Scope = 'Output'; s.Size = '60';
s = ss.addSymbol('path_y');      s.Scope = 'Output'; s.Size = '60';
s = ss.addSymbol('num_wp');      s.Scope = 'Output'; s.Size = '1';
s = ss.addSymbol('path_len');    s.Scope = 'Output'; s.Size = '1';
s = ss.addSymbol('state_code');  s.Scope = 'Output'; s.Size = '1';
s = ss.addSymbol('replan_flag'); s.Scope = 'Output'; s.Size = '1';
s = ss.addSymbol('plan_time');   s.Scope = 'Output'; s.Size = '1';
s = ss.addSymbol('mb');          s.Scope = 'Persistent'; s.Type = 'PythonObject';

projdir = strrep(fileparts(mfilename('fullpath')), '\', '\\');
init_code = sprintf([ ...
    'import sys, importlib\n' ...
    'p = r"%s"\n' ...
    'if p not in sys.path:\n' ...
    '    sys.path.insert(0, p)\n' ...
    'mb = importlib.import_module("matlab_bridge")\n' ...
    'mb.initialize_planner()\n'], projdir);
out_code = [ ...
    'import numpy as np' newline ...
    'gx, gy = float(goal[0]), float(goal[1])' newline ...
    'if mb._SESSION.goal != (gx, gy):' newline ...
    '    mb.set_goal(gx, gy)' newline ...
    'mb.update_obstacles([[float(r[0]), float(r[1]), float(r[2]), float(r[3]), float(r[4])] for r in np.atleast_2d(obs) if r[0] > 0])' newline ...
    'r = mb.plan_path(float(ego[0]), float(ego[1]), float(ego[3]))' newline ...
    'n = int(r["num_waypoints"]); m = min(n, 60)' newline ...
    'px = np.full(60, np.nan); py = np.full(60, np.nan)' newline ...
    'if m > 0:' newline ...
    '    px[:m] = np.asarray(r["path_x"][:m], dtype=float)' newline ...
    '    py[:m] = np.asarray(r["path_y"][:m], dtype=float)' newline ...
    'path_x = px; path_y = py' newline ...
    'num_wp = float(n); path_len = float(r["path_length_m"])' newline ...
    'state_code = float(r["planner_state_code"])' newline ...
    'replan_flag = 1.0 if r["replanned_this_call"] else 0.0' newline ...
    'plan_time = 1000.0 * float(r["planning_time"])' newline ...
    ];
set_param([model '/Python AStar Planner'], ...
    'InitializeConditionsCode', init_code, ...
    'OutputCode', out_code, ...
    'SampleTime', num2str(PLAN_DT));

% 4) EGO Motion (bounded kinematics via existing bridge logic) ------------
add_block('simulink/User-Defined Functions/Python Code', ...
    [model '/EGO Motion'], 'Position', [520 20 650 90]);
ss2 = get_param([model '/EGO Motion'], 'SymbolSpec');
s = ss2.addSymbol('ego');     s.Scope = 'Input';  s.Size = '4';
s = ss2.addSymbol('obs');     s.Scope = 'Input';  s.Size = '[8,5]';
s = ss2.addSymbol('ego_out'); s.Scope = 'Output'; s.Size = '4';
s = ss2.addSymbol('mb');      s.Scope = 'Persistent'; s.Type = 'PythonObject';
mot_code = [ ...
    'import numpy as np' newline ...
    'mb.update_obstacles([[float(r[0]), float(r[1]), float(r[2]), float(r[3]), float(r[4])] for r in np.atleast_2d(obs) if r[0] > 0])' newline ...
    'e = mb.ego_step(float(ego[0]), float(ego[1]), float(ego[2]), float(ego[3]), 0.02)' newline ...
    'ego_out = np.array([e["x"], e["y"], e["v"], e["heading"]], dtype=float)' newline ...
    ];
set_param([model '/EGO Motion'], ...
    'InitializeConditionsCode', init_code, ...
    'OutputCode', mot_code, ...
    'SampleTime', num2str(DT));

% 5) EGO state feedback (unit delay - physical continuity, no teleport) ---
add_block('simulink/Discrete/Unit Delay', [model '/EGO State Delay'], ...
    'InitialCondition', '[300;400;0;0]', 'SampleTime', num2str(DT), ...
    'Position', [430 300 470 340]);

% 6) Collision / Safety Validation ----------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model '/Collision Safety Validation'], 'Position', [520 130 680 200]);
set_matlab_function(model, 'Collision Safety Validation', char([ ...
"function [collision_count, min_clear_all, min_clear_now] = fcn(ego, obs)" newline ...
"% Independent MATLAB-side safety validation (matches bridge radii)." newline ...
"persistent cc mc" newline ...
"if isempty(cc), cc = 0; mc = inf; end" newline ...
"r = [19.8 30.8 34.1 15.4 11 11 3.85 12.1 13.2 16.5];" newline ...
"mn = inf;" newline ...
"for i = 1:8" newline ...
"    if obs(i,1) <= 0, continue; end" newline ...
"    d = hypot(ego(1)-obs(i,2), ego(2)-obs(i,3)) - 23 - r(int32(obs(i,1)));" newline ...
"    mn = min(mn, d);" newline ...
"end" newline ...
"if mn < 0, cc = cc + 1; end" newline ...
"if mn < mc, mc = mn; end" newline ...
"collision_count = cc; min_clear_all = mc; min_clear_now = mn;" newline ...
]));

% 7) Demux for scopes, Metrics sinks --------------------------------------
add_block('simulink/Signal Routing/Demux', [model '/EGO Demux'], ...
    'Outputs', '4', 'Position', [700 30 705 70]);

add_block('simulink/Sinks/Display', [model '/Collisions'], ...
    'Position', [880 20 950 40]);
add_block('simulink/Sinks/Display', [model '/Min Clearance (px)'], ...
    'Position', [880 60 950 80]);
add_block('simulink/Sinks/Display', [model '/Planner State'], ...
    'Position', [560 -60 640 -40]);
add_block('simulink/Sinks/Display', [model '/Replan Events'], ...
    'Position', [560 -100 640 -80]);

% Safety replan counter (event count from replan_flag edges)
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [model '/Replan Counter'], 'Position', [700 -110 830 -70]);
set_matlab_function(model, 'Replan Counter', char([ ...
"function n = fcn(flag)" newline ...
"persistent cnt prev" newline ...
"if isempty(cnt), cnt = 0; prev = 0; end" newline ...
"if flag > 0.5 && prev < 0.5, cnt = cnt + 1; end" newline ...
"prev = flag; n = cnt;" newline ...
]));

add_block('simulink/Sinks/Scope', [model '/Metrics Scope'], ...
    'Position', [880 140 910 180]);
add_block('simulink/Signal Routing/Mux', [model '/Scope Mux'], ...
    'Inputs', '4', 'Position', [820 135 825 185]);

add_block('simulink/Sinks/To Workspace', [model '/ego_log'], ...
    'VariableName', 'ego_log', 'SaveFormat', 'Array', ...
    'Position', [770 300 860 330]);
add_block('simulink/Sinks/To Workspace', [model '/planner_log'], ...
    'VariableName', 'planner_log', 'SaveFormat', 'Array', ...
    'Position', [770 380 860 410]);
add_block('simulink/Signal Routing/Mux', [model '/Planner Log Mux'], ...
    'Inputs', '6', 'Position', [700 375 705 425]);
add_block('simulink/Sinks/To Workspace', [model '/path_log'], ...
    'VariableName', 'path_log', 'SaveFormat', 'Array', ...
    'Position', [560 240 650 270]);
add_block('simulink/Sinks/To Workspace', [model '/safety_log'], ...
    'VariableName', 'safety_log', 'SaveFormat', 'Array', ...
    'Position', [880 220 970 250]);

%% --- Wiring ---------------------------------------------------------------
add_line(model, 'Simulation Time/1', 'Scenario Environment State/1', 'autorouting', 'on');

add_line(model, 'Scenario Environment State/1', 'Obstacle State/1', 'autorouting', 'on');
add_line(model, 'Obstacle State/1', 'Prediction/1', 'autorouting', 'on');
add_line(model, 'Obstacle State/1', 'Python AStar Planner/2', 'autorouting', 'on');
add_line(model, 'Obstacle State/1', 'EGO Motion/2', 'autorouting', 'on');
add_line(model, 'Obstacle State/1', 'Collision Safety Validation/2', 'autorouting', 'on');
add_line(model, 'Scenario Environment State/2', 'Python AStar Planner/3', 'autorouting', 'on');

add_line(model, 'EGO State Delay/1', 'Python AStar Planner/1', 'autorouting', 'on');
add_line(model, 'EGO State Delay/1', 'EGO Motion/1', 'autorouting', 'on');
add_line(model, 'EGO State Delay/1', 'Prediction/2', 'autorouting', 'on');
add_line(model, 'EGO State Delay/1', 'Collision Safety Validation/1', 'autorouting', 'on');
add_line(model, 'EGO State Delay/1', 'EGO Demux/1', 'autorouting', 'on');
add_line(model, 'EGO Motion/1', 'EGO State Delay/1', 'autorouting', 'on');

% Planner output ports: 1 path_x  2 path_y  3 num_wp  4 path_len
%                       5 state_code  6 replan_flag  7 plan_time
add_line(model, 'Prediction/1', 'safety_log/1', 'autorouting', 'on');
add_line(model, 'Collision Safety Validation/1', 'Collisions/1', 'autorouting', 'on');
add_line(model, 'Collision Safety Validation/2', 'Min Clearance (px)/1', 'autorouting', 'on');
add_line(model, 'Collision Safety Validation/3', 'Scope Mux/1', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/5', 'Planner State/1', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/6', 'Replan Counter/1', 'autorouting', 'on');
add_line(model, 'Replan Counter/1', 'Replan Events/1', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/7', 'Scope Mux/2', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/1', 'path_log/1', 'autorouting', 'on');

add_line(model, 'Scope Mux/1', 'Metrics Scope/1', 'autorouting', 'on');
add_line(model, 'EGO Demux/3', 'Scope Mux/3', 'autorouting', 'on');
add_line(model, 'Prediction/2', 'Scope Mux/4', 'autorouting', 'on');

add_line(model, 'EGO Motion/1', 'ego_log/1', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/3', 'Planner Log Mux/1', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/4', 'Planner Log Mux/2', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/5', 'Planner Log Mux/3', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/6', 'Planner Log Mux/4', 'autorouting', 'on');
add_line(model, 'Python AStar Planner/7', 'Planner Log Mux/5', 'autorouting', 'on');
add_line(model, 'Collision Safety Validation/3', 'Planner Log Mux/6', 'autorouting', 'on');
add_line(model, 'Planner Log Mux/1', 'planner_log/1', 'autorouting', 'on');

%% --- Solver & save ---------------------------------------------------------
set_param(model, 'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(DT), 'StopTime', '20');
save_system(model, [model '.slx']);
fprintf('Model saved: %s.slx\n', model);
end

% =========================================================================
function set_matlab_function(model, blkname, code)
rt = sfroot;
ch = rt.find('-isa', 'Stateflow.EMChart', 'Path', [model '/' blkname]);
ch.Script = code;
end
